- lib/utils.ts
Resolves #3 
A slight modification of `classNames` function that returns a unique string solves the duplicate classNames issue
> Handle duplicate classes

- pages/documents/new.tsx
Resolves #10 
Changes description text from
> "This is description will help you find your document later."
to
> "This description will help you find your document later."
> fix description typo

- .env.example
- Change POSTGRES_URL_NON_POOLING to POSTGRES_PRISMA_URL_NON_POOLING in .env.example
- Prisma schema is looking for `POSTGRES_PRISMA_URL_NON_POOLING`
-
> fix: update to correct .env variable in .env.example file

- components/links/links-table.tsx
This issue occurs because when the edit link button is clicked on the Actions dropdown, this dropdown does not get a chance to close before opening the edit link pop-up. 
#102
> Fix for page freeze after clicking on edit link option

- components/Sidebar.tsx
its realted to open issues #118 
with the provided changes the email is always going to be in the provided container 
before :
After:
> fixing the email ui

- components/web/footer.tsx
The logo in the header has 'tracking-tighter' whereas, in the footer, there's no tracking applied. Fixed this.
Before:
After:
> Update Papermark logo's tracking in footer

- app/(static)/open-source-investors/ClientPage.tsx
The client page's hero message was looking a bit odd. Added tracking-tighter here too (previously did this with the footer logo) and it looks a lot more elegant now.
There are a lot of other places as well where the font tracking needs to be tighter so as to match the overall aesthetics of the brand. Perhaps, would create another PR incorporating these updates.
> Fixed the tracking in Client page Hero message

- components/documents/stats-card.tsx
Typo in /documents page: Total avgerage view duration
> fix: typo in /documents page

- pages/api/assistants/index.ts
- pages/documents/[id]/index.tsx
Current AI assistant de-activation option is not working, this PR fixes it. #192 
Changes summary:
- Deleting the file from `OpenAI` after disabling the assistant, potentially leading to cost savings.
- In the `DocumentVersion` table, updating `FileId` as null.
- In the `Document` table, updating `AssistantEnabled` to false.
These changes have been locally validated and are functioning as expected.
Here's working demo: 
https://github.com/mfts/papermark/assets/39481600/916d0fd4-4b16-4b62-98ae-7b7397ea0de1
> Implemented changes to de-activating AI Assistant

- pages/settings/general.tsx
Fixe**d the `Save changes` button bug by adding a condition at the top of the function**, and also added another condition on button to **disable it when the team name is updating.**
Before changes
https://github.com/mfts/papermark/assets/87828904/3a5ffe91-e19e-4fcd-abcc-7d366334cdaa
After changes
https://github.com/mfts/papermark/assets/87828904/5f826e3f-1ca6-4acb-9734-dd4a06d14d51
#189
> 🪲 bugFix - fixed the save changes button bug by adding a condition

- components/documents/add-document-modal.tsx
I have successfully implemented a condition to verify whether a URL is valid or not. Moreover, I have incorporated a check to ensure that the URL is a valid Notion URL to prevent users from adding an invalid URL accidentally.
1. Created a variable named `validateNotionPageURL` to check if it's a valid notion page URL or not.
2. Created another variable named `isValidURL` which continues some Regc to check if it's a valid  URL or not.
3. Added a `condition` to validate user-given URL
https://github.com/mfts/papermark/assets/87828904/dfc8dbfe-d9e0-463b-b45b-398db48e31b8
Closes #201
> fix - fixed the Notion page URL validation bug

- components/documents/add-document-modal.tsx
**I've implemented 2 major features in this PR:**
1. **Automatic Notion Name Implementation**: When a Notion URL is pasted, a `function`  named  `createNotionFileName` will automatically extract the Notion page name and set it as the file name. This eliminates the same file name confusion.
2. **Handle same file name**: If a file with the same name already exists, the `function`  named  `createNotionFileName` will automatically append a counter ("1", "2", etc.) to the new file name, preventing overwriting and confusion.
1.  Added a new function named `createNotionFileName` to extract name from the Notion URL and also to add a counter("1", "2", etc.)  on the name if the same name already exists.
https://github.com/mfts/papermark/assets/87828904/4923fa85-41ea-4662-b7a9-9fb98df4b4a3
Closes …
> ✨ feature - Automatic Notion file name implementation

- components/documents/add-document-modal.tsx
I have created a function called `clearModelState` that clears the model documents or links once the model is closed. 
The function will execute only if the Document model has previously selected a document or link.
1. Created a function named `clearModelState` to clear model states.
2. Added conditions to the states to prevent them from being called without any data.
3. Attached the function with the `Dialog` component.
https://github.com/mfts/papermark/assets/87828904/e29b1892-f6d6-4468-8fa4-2b6f08624f68
Closes #217
> ♻️ refactor: document upload model data will get clear after closing it

- components/documents/add-document-modal.tsx
- pages/api/teams/[teamId]/documents/index.ts
**Added validation to check whether the Notion page is publically accessible or not.** If the Notion page is not accessible it will terminate the process and will return an error message to the user.
1. Validation added to check if the Notion page is publically accessible before saving to the database.
2. Implemented try-catch to handle errors and prevent global error messages.
3. Updated the user-facing error message to clarify the issue properly
https://github.com/mfts/papermark/assets/87828904/0d24c3b4-23b3-40ff-825f-8b8cdb0582e8
Closes #221
> fix: added validation to check whether the Notion page is public or private

- components/links/link-sheet/allow-list-section.tsx
- components/links/link-sheet/deny-list-section.tsx
- components/links/link-sheet/email-authentication-section.tsx
- components/links/link-sheet/email-protection-section.tsx
- components/links/link-sheet/index.tsx
- components/links/links-table.tsx
- components/ui/accordion.tsx
- components/ui/scroll-area.tsx
- lib/utils.ts
- package-lock.json
- package.json
- pages/api/links/[id]/index.ts
- pages/api/links/index.ts
- pages/api/views.ts
- prisma/migrations/20240215035046_add_allow_deny_list_to_links/migration.sql
- prisma/schema.prisma
- tailwind.config.js
> feat: allowlist and denylist

- pages/pricing.tsx
Currently, the `View Github` button on the pricing page on the banner `Looking to self-host?` has the same calendar link for `Book a demo`.
Changed the View Github link to this repo. https://github.com/mfts/papermark 
My cursor was on View Github button
fixes: https://github.com/mfts/papermark/issues/304
> fix: view github link on pricing page

- components/view/PagesViewer.tsx
- components/view/document-view.tsx
- components/view/nav.tsx
- components/view/powered-by.tsx
- components/view/view-data.tsx
- lib/types.ts
- pages/api/links/[id]/index.ts
- pages/view/[linkId]/index.tsx
first step towards revamping the viewing mode
> feat: add powered by button

- components/view/DataroomViewer.tsx
- components/view/PagesViewer.tsx
- components/view/dataroom/dataroom-view.tsx
- components/view/document-view.tsx
- pages/api/views-dataroom.ts
- pages/api/views.ts
- allow viewer to view a session in dataroom
- allow viewer to view a document
- disallow forwarding of token (only valid once)
> feat: improve email verification procedure and resetting the token after each visit

- components/documents/document-card.tsx
- components/documents/documents-list.tsx
- components/documents/drag-and-drop/draggable-item.tsx
- components/documents/drag-and-drop/droppable-folder.tsx
- components/documents/folder-card.tsx
- components/ui/portal.tsx
- package-lock.json
- package.json
- pages/api/teams/[teamId]/documents/move.ts
- pages/documents/index.tsx
- pages/documents/tree/[...name].tsx
- multi-select documents
- drag and drop to move document to folder
> feat: drag-drop documents into folder

- components/datarooms/dataroom-document-card.tsx
- components/datarooms/dataroom-items-list.tsx
- components/datarooms/folders/selection-tree.tsx
- components/datarooms/move-dataroom-folder-modal.tsx
- components/documents/move-folder-modal.tsx
- pages/api/teams/[teamId]/datarooms/[id]/documents/[documentId]/index.ts
- pages/api/teams/[teamId]/datarooms/[id]/documents/move.ts
- pages/datarooms/[id]/documents/[...name].tsx
- pages/datarooms/[id]/documents/index.tsx
- add move to home folder
- drag to move documents
> feat(datarooms): add drag to move documents to folder

- pages/datarooms/index.tsx
Fixes issue #587 
Ensuring that if user hasnt opted for any plan that is he is having free plan and no trial as well then no access to this dataroom route.
If user has lets say business plan but no trial at the moment,he can visit this dataroom page,he shudnt be redirected
> Fix/made the dataroom route protected in case user hasn't opted for any trial or plan

- components/datarooms/settings/duplicate-dataroom.tsx
- components/ui/card.tsx
This PR fix the issue: https://github.com/mfts/papermark/issues/652
- Fix error mesage
- Show update plan modal when limit reached
- The data room box name appears cut off at the bottom; this has also been fixed.
If we directly show the "Upgrade Plan" button, users will never encounter an error. However, if we allow them to duplicate the data room even after reaching the limit, the correct error message will now be displayed instead of not showing right error message previously.
> Handle Duplicate Data Room Error and Display Subscription Modal When Limit Reached

- pages/datarooms/[id]/groups/index.tsx
> fix: remove black color for subheading in dataroom groups page

- README.md
This pull request updates the "Prerequisites" section of the README to specify the correct Node.js version requirement for Next.js. The current README mentions "Node.js (version >= 18)," which can lead to compatibility issues for users running earlier versions of Node 18.
fixes #704
> Update Node.js version requirement to >= 18.17.0 in README

- components/links/link-sheet/agreement-panel/index.tsx
- components/view/access-form/agreement-section.tsx
- components/view/access-form/index.tsx
- components/view/dataroom/dataroom-view.tsx
- components/view/document-view.tsx
fixes #651 
I have utilised the name field of the agreement to show instead of NDA or privacy policy which were hardcoded. I have tested locally when the linkType was DATAROOM.
but for linkType as DOCUMENT, I am unable to do so as I am encountering an error on viewing an uploaded document 
this error is not on production, I am still trying to figure what might have caused this.
> feat: make agreement name customizable

- app/(auth)/login/page.tsx
fixes #711  
Created a single state for both loading and disabling buttons.
This code not only adds a single state to the Login page but also reduces the use of separate loaders without affecting any error handling in the form. No need to maintain separate states for each button.
```typescript
const [isLoginWithEmail, setIsLoginWithEmail] = useState<boolean>(false);
const [isLoginWithGoogle, setIsLoginWithGoogle] = useState<boolean>(false);
const [isLoginWithLinkedIn, setIsLoginWithLinkedIn] =
useState<boolean>(false);
``` 
```typescript
const [clickedMethod, setClickedMethod] = useState<AuthMethod | undefined>(
undefined,
);
``` 
```typescript
<Button
onClick={() => {
setIsLoginWithLinkedIn(true);
signIn("linkedin", {
...(next && next.length > 0 ? { callbackUrl: next } : {}), …
```
> fix: Single State for Button Disable and Loading

- app/(auth)/login/page.tsx
- components/hooks/useLastUsed.tsx
- lib/webstorage.ts
I added a last used text on login form and im using local storage the value 
Fixes #707 
[screen-capture (22).webm](https://github.com/user-attachments/assets/f2849799-9154-46cc-a84d-a16d7ef5245a)
> feat: added last_used in login page

- pages/documents/index.tsx
fixes #752 
This PR addresses the inconsistent spacing on the https://app.papermark.io/documents on mobile view. Adjustments have been made to ensure a more uniform and visually appealing layout.
> fix: add proper spacing to add-document-button

- components/datarooms/add-dataroom-modal.tsx
- components/datarooms/dataroom-trial-modal.tsx
- components/datarooms/settings/duplicate-dataroom.tsx
- components/documents/add-document-modal.tsx
- components/documents/document-card.tsx
- components/documents/document-header.tsx
Fixes https://github.com/mfts/papermark/issues/677
- The user can create a data room using the "Action" tabs if they have the correct subscription; otherwise, an "Upgrade Plan" tab will be shown.
- Display a tooltip for "Upload a new version." (The problem is that if we wrap the button with a tooltip, the button event doesn't work.)
> Improve document 📄 "Action" tab

- components/documents/document-card.tsx
- components/links/links-table.tsx
Fixes #854
Added condition with the help of `useLimits` hooks to restrict creating of links on free version in links table.
Disabled duplicate document option
Links Table
> fix: disabled to create links & duplicate documents due to free version limit

- components/Sidebar.tsx
The Papermark logo on the top left on the sidebar should redirect to /documents when clicked
Fixes #772
> fix: The Papermark logo on the top left on the sidebar should redirect to /documents when clicked

- components/Sidebar.tsx
Fixes: #772 
This PR implements a feature where clicking on the Papermark logo now redirects the user to the /document.This change improves navigation by providing a direct link to the document section, enhancing user accessibility.
Changes:
Updated the logo's link to point to /document.
Ensured that the routing is correctly handled without breaking any other functionality.
> Feat: papermark logo redirect to /document

- components/datarooms/folders/view-tree.tsx
- components/view/DataroomViewer.tsx
- components/view/dataroom/dataroom-view.tsx
@mfts Sorry my pr got deleted by mistake. I pushed the changes with new pr.
> fix: Keep state in dataroom view between document and dataroom view #783

- pages/settings/branding.tsx
The Problem : 
on smaller devices on the branding page the preview of the navbar and frontpage doesn't seem to be scroll showing only half the full image that's displayed on larger devices
it is unscrollable, doesnt let the user see the entire image 
What does this PR do : 
it fixes this problem and makes both the navbar and frontpage scrollable on smaller devices 
users can effectively scroll across the image even on smaller devices enabling them to see the full pic
ps: couldn't capture a video because of my system but i assure this works
> fix: the unscrollability across the /settings/branding page across navbar-and-frontpage

- pages/settings/people.tsx
> [Fix]:Added Overflow-auto and Gap for team members details

- components/billing/upgrade-plan-modal.tsx
- pages/settings/upgrade.tsx
This PR partially address https://github.com/mfts/papermark/issues/981 as loading state is fixed on other commit (reopening since #982 got auto locked)
The button backdrop getting merged with the background in dark mode.
Current version: **(the screen recording app cause that flickers when modal is open)**
https://github.com/user-attachments/assets/8e258771-9891-48f6-99ad-4b93d6750bab
Fix:
https://github.com/user-attachments/assets/350a6ef5-3e62-4eea-8d8a-806d38630586
> fix: Upgrade button dark mode visibility

- components/view/DataroomViewer.tsx
> 951-View dataroom folder tree list and documnet list ui fix

- components/documents/documents-list.tsx
- components/ui/nextra-filetree.tsx
- pages/documents/index.tsx
This PR addresses margin and padding issues in the DocumentList and Tree components. The following changes were made
Current version:
1. Search is overlapped 
2. In documents list there is no space at bottom on the last document card
3. The folder and also files on hovering in tree structure it lacks some space inbetween.
Fixed:
1 ![image](https://github.com/user-attachments/assets/6fac6954-6986-43cf-88c2-e673c3ad296e)
2 ![image](https://github.com/user-attachments/assets/48c2e0bf-8bec-4dad-b941-f0d597251373)
3 ![image](https://github.com/user-attachments/assets/2cc4b513-0d88-430d-a93f-a2c6a4c36c20)
> fix: resolve margin issues in DocumentList and Tree components

- components/document-upload.tsx
Fixes: #1184 
Truncated the filenames if they are large.
> fix: truncate long file names for better ui display

- components/NotionPage.tsx
- components/view/dataroom/dataroom-view.tsx
- components/view/dataroom/document-card.tsx
- components/view/document-view.tsx
- components/view/view-data.tsx
- lib/types.ts
- pages/api/views-dataroom.ts
- pages/view/[linkId]/index.tsx
- pages/view/domains/[domain]/[slug]/index.tsx
fixes #791 
Summary of changes: passed mode as the url param in the notion link and update the darkMode value in Notion doc
> fix: pass theme option as url params

- components/links/link-sheet/og-section.tsx
- components/links/link-sheet/watermark-panel/index.tsx
- components/links/link-sheet/watermark-section.tsx
Fixes : #1046 
First Fix: Link Sheet toggles hidden on mobile devices when "custom social media card toggle" active
Second Fix: 
seconf Fix: on 2 places
> 1046 [BUG] Link Sheet toggles hidden on mobile devices when "custom social media card toggle" active

- pages/datarooms/[id]/branding/index.tsx
- pages/datarooms/[id]/groups/index.tsx
- pages/settings/branding.tsx
Fixes #1311 
Added the missing link for How to customize data room branding? in branding screen
> fix: added missing link in branding

- components/links/link-sheet/link-options.tsx
- components/visitors/dataroom-visitor-useragent.tsx
- components/visitors/dataroom-visitors-table.tsx
- components/visitors/visitor-useragent-base.tsx
- ee/limits/constants.ts
- ee/limits/server.ts
- ee/limits/swr-handler.ts
- lib/swr/use-dataroom-stats.ts
- pages/api/teams/[teamId]/datarooms/[id]/views/[viewId]/user-agent.ts
- add location info to dataroom visitors
- add watermark on business via limits
> chore: improvements

- lib/notion/utils.ts
- pages/api/file/notion/index.ts
- pages/api/views-dataroom.ts
- pages/view/[linkId]/index.tsx
for new way how notion handles file signatures
> feat(notion): add signed file url script

- components/layouts/breadcrumb.tsx
- next.config.mjs
#1464 :
- Added a redirect in next.config.js to ensure /settings automatically navigates to /settings/general.
- Updated the Breadcrumb component to link "Settings" to /settings/general instead of /settings.
- Clicking "Settings" now correctly redirects to /settings/general.
- Ensures consistent navigation and prevents 404 issues when accessing /settings.
> 1464-fix 404 for Breadcrumb settings

- components/billing/upgrade-plan-modal.tsx
Hi @mfts,
This PR Fixes #1559
Background and text are made visible in dark mode in plan selector
https://github.com/user-attachments/assets/3a2a13c8-3ba3-415f-b599-0c96e7a687f9
> fix: inconsistent theme in plan selector

- .env.example
`env.example` file is missing this variable.
> chore: app base host env for local dev
