mfts/papermark

pages/api/documents.ts, pages/view/[linkId].tsx
=> fix: use extension of file instead of name to determine which viewer to use

pages/404.tsx
=> Add 404 page

components/Sidebar.tsx, pages/documents.tsx
=> Show empty state when there are no documents available

.gitignore, components/emails/welcome.tsx, lib/emails/send-welcome.ts, lib/resend.ts, lib/types.ts, package-lock.json, package.json, pages/api/auth/[...nextauth].ts
- universal utility function for resend 
- integrated with next-auth auth process
- email scaffolding with react-email
=> feat: add welcome email to new users

pages/api/links/[id]/index.ts
=> feat: delete link

pages/api/documents/[id]/index.ts
=> Document delete

components/view/document-view.tsx, pages/documents/[id].tsx, pages/view/[linkId].tsx, pages/view/domains/[domain]/[slug]/index.tsx
Added LoadingSpinner for loading wherever it as missing.
Fix: #97
=> Added LoadingSpinner for loading

Pipfile.lock, components/PagesViewer.tsx, components/documents/document-card.tsx, components/shared/blur-image.tsx, components/view/document-view.tsx, lib/swr/use-document.ts, lib/types.ts, next.config.js, pages/api/documents/[id]/index.ts, pages/api/documents/[id]/stats.ts, pages/api/documents/[id]/views/index.ts, pages/api/documents/index.ts, pages/api/documents/update.ts, pages/api/links/[id]/visits.ts, pages/api/views.ts, pages/documents/[id].tsx, pkgx.yaml, prisma/migrations/20231013165123_create_document_version/migration.sql, prisma/migrations/20231014200337_create_document_pages/migration.sql, prisma/schema.prisma
- add new document versions (_not enabled in UI for now_)
- add multiple document pages
- add blur image component
=> feat: add multiple document versions and document pages

components/links/link-sheet/index.tsx
Modified the text for edit link to "Edit link" from "Create a new link".
#110
=> Change the text of edit link dialog box

components/settings/pricing.tsx, components/web/footer.tsx, middleware.ts, pages/pricing.tsx, pages/settings/billing.tsx, prisma/schema.prisma
-Pricing page
-Pricing inside app
=> Pricing updates

components/view/document-view.tsx, pages/404.tsx, pages/api/links/[id]/index.ts, pages/api/links/domains/[...domainSlug].ts, pages/view/[linkId].tsx, pages/view/domains/[domain]/[slug]/index.tsx
Users can view the document even after archiving the link #130 
Added proper error messages in the `NotFound` component.
#126
=> Archive Issue Fix

components/web/header.tsx, components/web/navbar.tsx, components/web/section2.tsx, components/web/testimonials.tsx, pages/index.tsx
- added blur effect to the navbar
- removed mt-8 to get of that black top bar which was not visible due to bg-white property of navbar.
- added some hovering effects
=> fix: some ui changes

components/PDFViewer.tsx, components/PagesViewer.tsx
closes #169 
Added event listener in PDFViewer and PagesViewer
=> feat/Keyboard shortcuts left/right arrow key to navigate documents

lib/swr/use-teams.ts
=> fix: request to api/teams when user is not logged in

components/documents/add-document-modal.tsx
=> allow user to retry/re-upload after document upload fails. prevent indefinite loading

app/(auth)/login/page.tsx, components/Sidebar.tsx
this PR fixes: #206, #207 and #208
=> ui: added loading states in signin buttons and sidebar skeleton

.env.example
I have included the passkey credentials on the `.env.example` file.
Closes #211
=> Listed out the passkey credentials

app/(auth)/login/page.tsx, app/(auth)/register/page.tsx
This PR removes the horizontal overflow in login and register routes for smaller screens. 
1. Go to login or register route
2. Shrink the window width up to some extent
#224 
None
=> fix: removed horizontal overflow

components/web/alternatives/featurestable.tsx, components/web/alternatives/pricingtable.tsx, pages/docsend-alternatives.tsx
Some textual and table updates for the website page Docsend Alternatives
=> Docsend alternatives page updates

components/links/link-sheet/index.tsx
=> UI Fix: Loader added in save link modal

components/Sidebar.tsx, components/theme-toggle.tsx, pages/documents/[id]/index.tsx
=> ui fixes: AI-Assistant activate/deactivate delay and sidebar scrolling issue 

components/links/link-sheet/feedback-section.tsx, components/links/link-sheet/index.tsx, components/links/links-table.tsx, components/view/PagesViewer.tsx, components/view/document-view.tsx, pages/api/links/[id]/index.ts, pages/api/links/index.ts, prisma/migrations/20240110233134_add_disable_feedback/migration.sql, prisma/schema.prisma
add `enableFeedback` to database to make disabling feedback persistent
=> feat: enable feedback per link

components/view/PagesViewer.tsx, components/view/toolbar.tsx, lib/files/get-file.ts, pages/api/links/download.ts
=> fix: reactions blocking navbar

components/documents/document-card.tsx
=> fix(278) - document card pdf icon color

.env.example, app/(static)/alternatives/[slug]/page.tsx, app/(static)/oss-friends/page.tsx, app/(static)/solutions/[slug]/page.tsx, app/page.tsx, components/view/PagesViewer.tsx, components/web/alternatives/alternativesgrid.tsx, components/web/alternatives/docsendtext.tsx, components/web/alternatives/papermarktext.tsx, components/web/section3.tsx, jobs/convert-pdf-to-image.ts, next.config.mjs, pages/ai.tsx, pages/share-notion-page.tsx
- also revalidate links after documents are processed
=> docs: simplify distributions url in next.config

components/documents/folder-card.tsx, components/folders/add-folder-modal.tsx, components/folders/edit-folder-modal.tsx, lib/resend.ts, pages/api/teams/[teamId]/datarooms/[id]/folders/manage/[folderId]/index.ts, pages/api/teams/[teamId]/datarooms/[id]/folders/manage/index.ts, pages/api/teams/[teamId]/folders/[...name].ts, pages/api/teams/[teamId]/folders/manage/[folderId]/index.ts, pages/api/teams/[teamId]/folders/manage/index.ts
- delete folder
- delete folder in datarooms
=> feat: delete folder

.env.example, lib/team/helper.ts, lib/utils.ts, pages/api/links/[id]/index.ts, pages/api/links/index.ts, pages/api/views-dataroom.ts, pages/api/views.ts
Issue -> https://github.com/mfts/papermark/issues/380
1.Added a new key named Docs_Password_Key
2.if (!textParts || textParts.length !== 2) applied this condition for old users, so they update their passwords
=> feat: refactor password show decrypted password for link

components/datarooms/add-dataroom-modal.tsx, ee/LICENSE, ee/limits/handler.ts, ee/limits/server.ts, ee/limits/swr-handler.ts, lib/swr/use-limits.ts, pages/api/teams/[teamId]/datarooms/index.ts, pages/api/teams/[teamId]/invite.ts, pages/api/teams/[teamId]/limits.ts, pages/datarooms/index.tsx, pages/settings/people.tsx, prisma/migrations/20240511000000_add_team_limits/migration.sql, prisma/schema.prisma
This PR also introduces the Papermark Enterprise Edition `ee` repo, which is [licensed](https://github.com/mfts/papermark/tree/main/ee/LICENSE) under a different license than the rest of the source code.
=> feat: check team limits

lib/api/notification-helper.ts, next.config.mjs, package-lock.json, package.json, pages/api/views.ts
- trigger was a short stop for such a simple function
=> feat: add waituntil for simple notifications 

components/billing/pro-banner.tsx, components/billing/upgrade-plan-modal.tsx, pages/pricing.tsx, pages/settings/billing.tsx
Updates of design and pricing pages, and pricing
=> chore: text updates and color fixes

components/view/dataroom/dataroom-view.tsx, components/view/document-view.tsx, components/view/view-data.tsx, components/view/viewer/advanced-excel-viewer.tsx, pages/api/views-dataroom.ts, pages/api/views.ts, pages/view/[linkId]/index.tsx, pages/view/domains/[domain]/[slug]/index.tsx
=> feat: add advanced excel viewer

components/document-upload.tsx
=> Fix: Updated supported file types for uploads

components/view/PagesViewerNew.tsx, components/view/nav.tsx
=> Revert "feat: improve zoom for documents"

app/(static)/help/page.tsx, components/web/footer.tsx
small updates on help center page
=> updates for help center page

app/api/trigger/route.ts, jobs/convert-pdf-to-image.ts, lib/files/put-file-server.ts, pages/api/mupdf/convert-page.ts
- choose the best file format based on file size (jpeg for color-heavy, png for text-heavy)
- choose the best scale factor based on pixel width of page
=> feat: improve file conversion

components/emails/onboarding-1.tsx, components/emails/onboarding-2.tsx, components/emails/onboarding-3.tsx, components/emails/onboarding-4.tsx, components/emails/onboarding-5.tsx, components/web/alternatives/docsendtext.tsx, lib/emails/send-onboarding.ts, pages/docsend-alternatives.tsx
Onboarding emails sequence and small changes on Docsend page
=> updates for the emails and small docend alternatives page

components/links/link-sheet/agreement-panel/index.tsx, components/view/access-form/agreement-section.tsx, components/view/access-form/email-section.tsx, components/view/access-form/index.tsx, components/view/dataroom/dataroom-view.tsx, components/view/document-view.tsx, pages/api/teams/[teamId]/agreements/index.ts, pages/view/[linkId]/index.tsx, pages/view/domains/[domain]/[slug]/index.tsx, prisma/migrations/20240821000000_add_require_name/migration.sql, prisma/schema.prisma
- make viewerName optional on agreement
- add query param for disabling email editing
=> feat: enable mailmerge

components/ui/button.tsx
=> fix/changed text color of Upgrade btn on settings/billing page

pages/documents/[id]/index.tsx
=> fixed error handling of documents/[id] page for handling 400 bad request

next.config.mjs, pages/api/jobs/send-dataroom-new-document-notification.ts, pages/api/jobs/send-dataroom-view-invitation.ts, prisma/migrations/20240921000000_add_viewer_migration/migration.sql, prisma/schema.prisma
- change unique index to teamId and email
=> feat(prisma): adjust viewer table model

components/billing/upgrade-plan-modal.tsx, package-lock.json, pages/settings/upgrade.tsx
fixes issue #631 
- Fixed issues with inconsistent theming in various components 
- Fixed UI issues in both light and dark modes.
- Standardized theme colors for better contrast and readability.
- **Testing**:
- Manually tested light/dark mode across the app for consistency.
- **Screenshot**
=> Fixed issues with inconsistent theming in various components

oss-gg/oss-gg-quests/1-record-your-first-user-experience.md
- fixes/completes #638 
- fixes/completes #633
=> feat:adding side quest tracking file

oss-gg/oss-gg-quests/1-record-your-first-user-experience.md
Related to #633 
Here is my PR for the record your first user experience challenge: [recording](https://www.loom.com/share/3190223108594d6fa10ccfdd9cab6f4e?sid=aabdf87d-12c4-4486-a2b5-c9a6feac6f43)
Also added my name to the file in the oss-gg folder. Should we create other side quests related file when we submit?
=> ossgg: Add submission for record onbording

pages/api/links/index.ts
=> chore: update index.ts

oss-gg/9-record-your-first-user-experience.md
Related to #633
I have provided a detailed review of PaperView.io and suggested some changes. The video consists of two parts. All the feedback comes from me as a non-user of the product.
=> ossgg: Added my submission for record onbording

oss-gg/3-follow-linkedin.md, oss-gg/5-follow-twitter-x.md, oss-gg/8-design-new-logo-papermark.md
Created a new logo:
Link: https://dub.sh/GAsHMmo
Followed on X:
Followed on LinkedIn:
=> feat: Logo, X and LinkedIn follow [SIDE QUEST]

oss-gg/3-follow-linkedin.md, oss-gg/5-follow-twitter-x.md, oss-gg/8-design-new-logo-papermark.md
Fixes issue: #662 
PR to submit side quests: 
Follow [Papermark X (Twitter)](https://x.com/papermarkio) Account (50 Points)
Follow [Papermark LinkedIn](https://linkedin.com/company/papermarkio) Page (50 Points)
Design our new Papermark logo (150 Points per logo, 750 for the winner)
=> oss.gg: Follow on X, LinkedIn and logo submission

components/datarooms/add-dataroom-modal.tsx
This PR fix the issue: https://github.com/mfts/papermark/issues/672
=> fix dataroom delete equal name issue

pages/documents/index.tsx
=> Handled error on /documents page if there is error fetching documents from server

oss-gg/1-meme-magic.md, oss-gg/2-gif-magic.md, oss-gg/3-follow-linkedin.md, oss-gg/5-follow-twitter-x.md, oss-gg/8-design-new-logo-papermark.md
- Meme Magic 
- GIF Magic
- Logo creation : #680
=> oss.gg:no-code side quest

components/upload-zone.tsx
Fixed the drop Zone, Now user can drop files easily.
=> Fix : #679

oss-gg/1-meme-magic.md, oss-gg/2-gif-magic.md, oss-gg/3-follow-linkedin.md, oss-gg/5-follow-twitter-x.md, oss-gg/8-design-new-logo-papermark.md
- Meme Magic
- Gif Magic
- Logo Creation : [Link to Logo](https://drive.google.com/file/d/18X4S1rQgltp9j0o5aX3-bO8FmemWjgVC/view)
I have read the CLA Document and I hereby sign the CLA
=> oss.gg:no-code-side-quest

pages/404.tsx
=> fix: inconsistent theme in 404 screen

oss-gg/9-record-your-first-user-experience.md
=> First user experience SideQuests

README.md, package.json
Added npx prisma generate && npx prisma migrate deploy for dev:prisma script and Updated readme 
Issue : #723
=> Added Script for Prisma 

components/Sidebar.tsx, components/billing/upgrade-plan-modal.tsx
Small changes for progress bar and fix on upgrade screen
=> feat: added small changes to side bar and upgrade modal

README.md
This PR updates the missing PostgreSQL link
=> chore:add missing  PostgreSQL link

components/document-upload.tsx, components/upload-zone.tsx
Fixed #761 
Updated the supported extensions in `document-upload` and `upload-zone`
=> fix: added all supported extensions in the file uploads

app/(auth)/login/page.tsx
Fixes #875
The login page should should always be in light theme
=> Fix - login page should always be in light theme

oss-gg/1-meme-magic.md
the notion says create meme about paper, so replace the brick with paper here
=> replace word "brick" with "paper" in meme magic list

oss-gg/2-gif-magic.md
I just replace the brick word with the thing mentiond in notion page, noth else.
---
=> replace "Brick" with "papermark" in gif list

components/documents/document-card.tsx, components/search-box.tsx, lib/swr/use-documents.ts, pages/api/teams/[teamId]/documents/index.ts, pages/api/teams/[teamId]/documents/search.ts, pages/documents/index.tsx
Adding search bar to documents page, in progress
=> feat: search_bar

components/billing/upgrade-plan-modal.tsx, pages/settings/upgrade.tsx, signatures/version1/cla.json
- Fix the loading problem, when user purchase subscription.
- change the text color in dark mode.
- remove unwated CSS
- Before
https://github.com/user-attachments/assets/54414609-aef7-400a-a098-6026b2f0e28e
https://github.com/user-attachments/assets/ca561edf-4f75-4b9e-b5ba-5e0d5570e718
- After
https://github.com/user-attachments/assets/4add00c6-1d9d-4c07-be8c-b002976a2c65
https://github.com/user-attachments/assets/bc0df25b-cefe-47ba-8596-0815c08a5bc1
=> Improve Loading Performance and UI in dark mode

components/datarooms/move-dataroom-folder-modal.tsx, components/documents/move-folder-modal.tsx
resolves #938 
made the folders scrollable and restricted max height of modal
tested functionality, have attached working video & screenshot for reference
https://github.com/user-attachments/assets/e2f94159-8581-4b85-b991-1e67ed5ad04f
=> fixes #938 adds scrollbar to add folder modal 

README.md
This pull request includes several improvements to the documentation for Papermark. Key changes made include:
- Fixed minor typos and grammatical errors.
- Enhanced clarity and consistency in phrasing throughout the document.
- Improved the formatting of lists for better readability.
These updates aim to make the documentation more user-friendly and accessible for new contributors and users. Please review the changes and let me know if there are any additional suggestions or adjustments needed. Thank you!
=> Fix Typos and Improve Clarity in Documentation

components/datarooms/groups/add-group-modal.tsx, components/teams/add-team-modal.tsx, pages/datarooms/[id]/groups/[groupId]/index.tsx, pages/settings/general.tsx
=> 1163 Fix delete team and group issue

components/billing/plan-badge.tsx, components/documents/document-header.tsx, components/links/link-sheet/agreement-section.tsx, components/links/link-sheet/allow-download-section.tsx, components/links/link-sheet/allow-list-section.tsx, components/links/link-sheet/allow-notification-section.tsx, components/links/link-sheet/deny-list-section.tsx, components/links/link-sheet/email-authentication-section.tsx, components/links/link-sheet/email-protection-section.tsx, components/links/link-sheet/expiration-section.tsx, components/links/link-sheet/feedback-section.tsx, components/links/link-sheet/link-item.tsx, components/links/link-sheet/og-section.tsx, components/links/link-sheet/password-section.tsx, components/links/link-sheet/question-section.tsx, components/links/link-sheet/screenshot-protection-section.tsx, components/links/link-sheet/watermark-section.tsx, components/ui/tooltip.tsx, lib/tinybird/pipes.ts, pages/settings/branding.tsx, pages/settings/domains.tsx, pages/settings/presets.tsx
fixes #1229 
I also added some information tips for other places as mentioned.
=> #1229 Add help / info tips to link settings

components/links/link-sheet/question-section.tsx
=> Fixed hover issue in create link

components/datarooms/dataroom-document-card.tsx, components/documents/add-document-to-dataroom-modal.tsx
fixes #699 
- User can add docs one dataroom to onther dataroom
=> add doc one dataroom to second

components/documents/add-folder-to-dataroom-modal.tsx, components/documents/folder-card.tsx, pages/api/teams/[teamId]/datarooms/[id]/folders/manage/[folderId]/dataroom-to-dataroom.ts
=> Add dataroom folder to other dataroom

components/documents/filters/sort-button.tsx, components/search-box.tsx, pages/api/teams/[teamId]/documents/index.ts
Ref #1290 
Added two new sorting options:
1. Sort by name
2. Sort by number of links
=> feat: add additional sorting options for documents

components/welcome/dataroom-upload.tsx, components/welcome/notion-form.tsx, components/welcome/special-upload.tsx, components/welcome/upload.tsx
fixed #1275 
@mfts  Fixed now!
I encountered this error, but after removing the .next folder and node_modules, it was resolved! 
If this issue arises again in the future.
=> Fixed create link issue

components/welcome/dataroom-upload.tsx
=> Fix DR trial link fails

components/documents/add-document-modal.tsx
=> Fix notion file upload

components/layouts/app.tsx
=> Fixed: Two scroll bars appear on small screens on almost every page

components/visitors/visitor-avatar.tsx, components/visitors/visitors-table.tsx, lib/swr/use-document.ts, lib/swr/use-stats.ts, lib/tinybird/endpoints/get_total_average_page_duration.pipe, lib/tinybird/pipes.ts, pages/api/teams/[teamId]/documents/[id]/stats.ts, pages/api/teams/[teamId]/views/[id]/archive.ts, pages/documents/[id]/index.tsx, prisma/migrations/20241029000000_add_archived_view/migration.sql, prisma/schema.prisma
and by association remove them from the document statistics
=> feat: add ability to archive views

components/document-upload.tsx, components/shared/icons/files/map.tsx, components/upload-zone.tsx, lib/constants.ts, lib/documents/create-document.ts, lib/tinybird/pipes.ts, lib/utils/get-content-type.ts, lib/utils/get-file-icon.tsx, pages/api/teams/[teamId]/documents/index.ts
=> feat: add support for kml / kmz file type

components/documents/documents-list.tsx, components/upload-zone.tsx, pages/documents/index.tsx
=> Fix ui on documents list page

app/(auth)/login/page.tsx, app/(auth)/verify/invitation/AcceptInvitationButton.tsx, app/(auth)/verify/invitation/page.tsx, components/view/visitor-graph.tsx, lib/middleware/app.ts, lib/utils.ts, lib/utils/generate-jwt.ts, pages/api/teams/[teamId]/invitations/accept.ts, pages/api/teams/[teamId]/invitations/resend.ts, pages/api/teams/[teamId]/invite.ts, pages/documents/index.tsx, pages/settings/people.tsx
=> improve invitation accept
